name: Deploy Frontend React App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - closed    

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'

    - name: Install dependencies
      working-directory: 'frontend/ya_delivery'
      run: npm install --legacy-peer-deps

    - name: Build the React app
      working-directory: 'frontend/ya_delivery'
      env:
        CI: false
      run: npm run build

    - name: Install sshpass
      run: sudo apt update && sudo apt install -y sshpass

    - name: Deploy to server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        source: "frontend/ya_delivery/build/*"
        target: /root/ya_dostavka/webpack/
